#!/bin/bash

download_dir="EMG patterns of the neonatal mouse "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://plos.figshare.com/ndownloader/files/13490648" -O "$download_dir/scripts.zip"

