#!/bin/bash

download_dir="EMG and GRF data "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.mat
wget "https://figshare.com/ndownloader/articles/14642817/versions/1" -O "$download_dir/scripts.mat.zip"

