#!/bin/bash

download_dir="EMG : Thoracic Inspiratory Muscle "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.csv
wget "https://plos.figshare.com/ndownloader/files/28521709" -O "$download_dir/scripts.csv"

