#!/bin/bash

download_dir="EMG signals in very late-stage of Duchenne muscular dystrophy 2 "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://springernature.figshare.com/ndownloader/files/9207967" -O "$download_dir/scripts.zip"
