#!/bin/bash

download_dir="EMG Basketball Pitchers "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://figshare.com/ndownloader/files/12189134" -O "$download_dir/scripts.zip"

