#!/bin/bash

download_dir="EMG Pattern Recognition"  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://data.ncl.ac.uk/ndownloader/articles/10281629/versions/2" -O "$download_dir/scripts.mat.zip"


