#!/bin/bash

download_dir="EMG : Extending the limits of force endurance "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/dy89c6hg5b-2.zip" -O "$download_dir/scripts.zip"
