#!/bin/bash

download_dir="EMG Data for SSH"  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://figshare.com/ndownloader/articles/4684885/versions/1" -O "$download_dir/scripts.txt.zip"

