#!/bin/bash

download_dir=" Enhanced EEG-EMG Coherence Analysis "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/wfk9fv52sp-1.zip" -O "$download_dir/scripts.zip"
