#!/bin/bash

download_dir=" High-density EMG "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.zip
wget "https://figshare.com/ndownloader/articles/22227337/versions/1" -O "$download_dir/scripts.zip"
