#!/bin/bash

download_dir="kinematics and EMG of the forearm and hand"  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.mat
wget "https://zenodo.org/record/3337890/files/KIN_MUS_UJI.mat?download=1"  -O "$download_dir/scripts.mat"
