#!/bin/bash

download_dir="TKA Subject Raw EMG "  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Download scripts.mat
wget "https://figshare.com/ndownloader/files/34111076" -O "$download_dir/scripts.mat"

