#!/bin/bash

download_dir="UCI ML Repo 5"  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"



# Download scripts.zip
wget "https://archive.ics.uci.edu/static/public/481/emg+data+for+gestures.zip" -O "$download_dir/scripts.zip"
