#!/bin/bash

download_dir="UCI ML Repo 4"  # Replace with the desired directory path

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"



# Download scripts.zip
wget "https://archive.ics.uci.edu/static/public/313/semg+for+basic+hand+movements.zip" -O "$download_dir/scripts.zip"
